[workspace]
members = []
exclude = [
    "./tests/macro-tests",
    "./tests/other-tests",
    "./tests/proc-macro-tests",
    "./tests/virtual-workspace-tests",
    "./tests/workspace-tests",
]
resolver = "2"

[package]
name = "tryexpand"
description = "Test harness for macro expansion"
authors = ["Vincent Esche <regexident@gmail.com>", "eupn <eupn@protonmail.com>"]
repository = "https://github.com/regexident/tryexpand"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
rust-version = "1.70"
version = "0.6.0"

[dependencies]
base62 = "2.0.2"
basic-toml = "0.1"
cargo_metadata = "0.18.1"
cargo_toml = "0.18.0"
diff = "0.1"
glob = "0.3"
prettyplease = "0.2"
serde = { version = "1.0.195", features = ["derive"] }
syn = { version = "2", features = ["full"] }
thiserror = "1.0.56"
yansi = "0.5.1"
