[workspace]
members = []
exclude = ["./tests/proc-macro-tests", "./tests/macro-tests"]

[package]
name = "tryexpand"
version = "0.0.0"
edition = "2018"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/regexident/tryexpand"
authors = ["Vincent Esche <regexident@gmail.com>", "eupn <eupn@protonmail.com>"]
description = "Test harness for macro expansion"

[dependencies]
base62 = "2.0.2"
basic-toml = "0.1"
cargo_toml = "0.18.0"
diff = "0.1"
glob = "0.3"
prettyplease = "0.2"
scopeguard = "1.2.0"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0"
syn = { version = "2", features = ["full"] }
thiserror = "1.0.56"
yansi = "0.5.1"
