[workspace]
members = []
exclude = ["./tests/proc-macro-tests", "./tests/macro-tests"]

[package]
name = "tryexpand"
version = "1.0.9"                                      # remember to update in lib.rs
edition = "2018"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/regexident/tryexpand"
authors = ["eupn <eupn@protonmail.com>"]
description = "Test harness for macro expansion"

[dependencies]
basic-toml = "0.1"
diff = "0.1"
glob = "0.3"
prettyplease = "0.2"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0"
syn = { version = "2", features = ["full"] }
yansi = "0.5.1"

[[test]]
name = "integration"
path = "tests/macros/tests/tests.rs"
