[tasks.test]
command = "cargo"
args = ["test"]

[tasks.test-other]
command = "cargo"
args = [
    "test",
    "--manifest-path",
    "tests/other-tests/Cargo.toml",
    "--",
    "--test-threads=1",
]

[tasks.test-macros]
command = "cargo"
args = [
    "test",
    "--manifest-path",
    "tests/macro-tests/Cargo.toml",
    "--",
    "--test-threads=1",
]

[tasks.test-proc-macros]
command = "cargo"
args = [
    "test",
    "--manifest-path",
    "tests/proc-macro-tests/Cargo.toml",
    "--",
    "--test-threads=1",
]

[tasks.test-all]
dependencies = ["test", "test-other", "test-macros", "test-proc-macros"]
