[tasks.test]
command = "cargo"
args = ["test"]

[tasks.test-other]
command = "cargo"
args = [
    "test",
    "--manifest-path",
    "tests/other-tests/Cargo.toml",
    "--",
    "--test-threads=1",
]
env.RUST_BACKTRACE = "0"

[tasks.test-workspace]
dependencies = ["test-workspace-included", "test-workspace-excluded"]

[tasks.test-workspace-included]
command = "cargo"
args = [
    "test",
    "--manifest-path",
    "tests/workspace-tests/Cargo.toml",
    "--workspace",
    "--",
    "--test-threads=1",
]
env.RUST_BACKTRACE = "0"

[tasks.test-workspace-excluded]
command = "cargo"
args = [
    "test",
    "--manifest-path",
    "tests/workspace-tests/excluded-tests/Cargo.toml",
    "--",
    "--test-threads=1",
]
env.RUST_BACKTRACE = "0"

[tasks.test-virtual-workspace]
dependencies = [
    "test-virtual-workspace-included",
    "test-virtual-workspace-excluded",
]

[tasks.test-virtual-workspace-included]
command = "cargo"
args = [
    "test",
    "--manifest-path",
    "tests/virtual-workspace-tests/Cargo.toml",
    "--workspace",
    "--",
    "--test-threads=1",
]
env.RUST_BACKTRACE = "0"

[tasks.test-virtual-workspace-excluded]
command = "cargo"
args = [
    "test",
    "--manifest-path",
    "tests/virtual-workspace-tests/excluded-tests/Cargo.toml",
    "--",
    "--test-threads=1",
]
env.RUST_BACKTRACE = "0"

[tasks.test-macros]
command = "cargo"
args = [
    "test",
    "--manifest-path",
    "tests/macro-tests/Cargo.toml",
    "--",
    "--test-threads=1",
]
env.RUST_BACKTRACE = "0"

[tasks.test-proc-macros]
command = "cargo"
args = [
    "test",
    "--manifest-path",
    "tests/proc-macro-tests/Cargo.toml",
    "--",
    "--test-threads=1",
]
env.RUST_BACKTRACE = "0"

[tasks.test-all]
dependencies = [
    "test",
    "test-other",
    "test-workspace",
    "test-virtual-workspace",
    "test-macros",
    "test-proc-macros",
]
