name: Other

on:
    push:
      branches: [main]
    pull_request:
      branches: [main, "**"]
      paths-ignore:
        - "CHANGELOG.md"

jobs:
  validate-renovate:
    name: Validate Renovate's Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Validate Config
        uses: rinchsan/renovate-config-validator@af670950de28f7559f33d7b67e9f9d44f9c10048 # main
