name: Other

on:
    push:
      branches: [main]
    pull_request:
      branches: [main, "**"]
      paths-ignore:
        - "CHANGELOG.md"

jobs:
  validate-renovate:
    name: Validate Renovate's Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Validate Config
        uses: rinchsan/renovate-config-validator@59af5a77e6e4a61bd19af0e043e7200e778fc51f # main
