name: Other

on:
    push:
      branches: [main]
    pull_request:
      branches: [main, "**"]
      paths-ignore:
        - "CHANGELOG.md"

jobs:
  validate-renovate:
    name: Validate Renovate's Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Validate Config
        uses: rinchsan/renovate-config-validator@59af5a77e6e4a61bd19af0e043e7200e778fc51f # main
