name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "**"]
    paths-ignore:
      - "CHANGELOG.md"

jobs:
  info:
    name: Rust Info
    runs-on: ubuntu-latest
    steps:
      - name: Rustup Show
        shell: bash
        run: rustup show
      - name: Rustup Version
        shell: bash
        run: rustup --version

  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          # update `cargo-expand` accordingly, when bumping MSRV:
          toolchain: 1.88.0
          components: rust-src
      - uses: cargo-bins/cargo-binstall@f8ce4d55b131f4a1e373b8747ca6b6a54133ae5a # v1.18.0
      - run: cargo binstall cargo-expand@1.0.95 --no-confirm
      - run: cargo test
      - run: cargo test --manifest-path tests/other-tests/Cargo.toml -- --test-threads=1
      - run: cargo test --manifest-path tests/macro-tests/Cargo.toml -- --test-threads=1
      - run: cargo test --manifest-path tests/proc-macro-tests/Cargo.toml -- --test-threads=1
      - run: cargo test --manifest-path tests/virtual-workspace-tests/Cargo.toml --workspace -- --test-threads=1
      - run: cargo test --manifest-path tests/virtual-workspace-tests/excluded-tests/Cargo.toml -- --test-threads=1
      - run: cargo test --manifest-path tests/workspace-tests/Cargo.toml --workspace -- --test-threads=1
      - run: cargo test --manifest-path tests/workspace-tests/excluded-tests/Cargo.toml -- --test-threads=1

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy -- -D warnings

  minimal_versions:
    name: Compile and test with minimal versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@c92145f013402a7a11d63dc2303d45d4dae66699 # cargo-hack
      - uses: taiki-e/install-action@87ae565a2ff2d9e77a64fe09dd8f5eb233abf967 # cargo-minimal-versions
      - name: minimal-versions check
        run: cargo minimal-versions check --workspace --all-features --ignore-private -v
      - name: minimal-versions build
        run: cargo minimal-versions build --workspace --all-features --ignore-private -v
      - name: minimal-versions test
        run: cargo minimal-versions test --release --workspace --all-features -v
        continue-on-error: true

  msrv:
    name: Verify minimal supported rust version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@c92145f013402a7a11d63dc2303d45d4dae66699 # cargo-hack
      - run: cargo hack check --rust-version --workspace --all-targets --ignore-private
